---
title: C26112
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26112
helpviewer_keywords:
- C26112
ms.assetid: 926de738-b9b0-43d7-9137-ab2daa44ad4d
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: ebcd996f8d61cd885ee96c5e4ed19d8197767183
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/23/2019
ms.locfileid: "62426926"
---
# <a name="c26112"></a>C26112
Предупреждение C26112: Вызывающая сторона не может удерживать никакие блокировки до вызова метода \<func >.

 Заметка `_Requires_no_locks_held_` налагает предусловия, что вызывающий объект не должен удерживать никакие блокировки, пока он вызывает функцию. Предупреждение C26112 выдается при сбое функции снять все блокировки, прежде чем он вызывает другую функцию.

## <a name="example"></a>Пример
 В следующем примере возникает предупреждение C26112, так как `_Requires_no_locks_held_` предусловие нарушено вызов `NoLocksAllowed` в заблокированный раздел.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
} DATA;

_Requires_no_locks_held_

void NoLocksAllowed(DATA* p)
{
     // Lock sensitive operations here
}

void LocksHeldFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    NoLocksAllowed(p); // Warning C26112
    LeaveCriticalSection(&p->cs);
}
```