---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 0867c088e4bfb01a6b1ba9eeb75a7dc91c1321b5
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878883"
---
# <a name="c28198"></a>C28198
Предупреждение C28198: Возможна утечка памяти вследствие исключения.

 Это предупреждение означает, что выделенная память не освобождается после возникновения исключения. Инструкция в конце пути может вызвать исключение. Память была передана в функцию, которая могла сохранить копию для последующего освобождения.

 Это предупреждение очень похоже на предупреждение [C28197](../code-quality/c28197.md). Здесь также можно использовать заметки, Рекомендуемые для использования с предупреждением [C28197](../code-quality/c28197.md) .

## <a name="example"></a>Пример
 Следующий пример кода вызывает появление этого предупреждения.

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 Следующий пример кода позволяет избежать появления этого предупреждения.

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
